### PR TITLE
Add pacmanfigure

### PR DESCRIPTION
**Pull request by NGC0001**
currently, still using coin picture. no orientation changes.

### CODE REVIEW

**Comment by NGC0001** [comment]
What has been changed in this branch:
- Pacman figure logic added.
- Constructor for all `Item`s has been changed. Now width and height have to be specified, while x and y can be set with setX and setY.
- Name for some of the game items are now auto-generated. Refer to the code for more details.
- Speed of movable items is now frame rate independent.
- Pictures are move from data/GUI to data, with their filenames amended.
- All `PImage`s are now only loaded once.

**Review by M1s4kuy4 — APPROVED** [review]
The changes fit the description and meet the need, I think it could be merged.

**Comment by Lion2cat** [comment]
Great! Let's try to merge **pacmanfigure** into main.

**Review by Lion2cat — APPROVED** [review]
Great! Let's try to merge **pacmanfigure** into main.

**Pull request merged**
